### ISSUE TITLE
"Referrer" file

### ISSUE THREAD

**Issue by MoskalykA** [MoskalykA/rt#2]
Allows a file to clearly reference other files.

I currently have to do this:
```yaml
tasks:

files:
  - dashboard/rt.yaml
  - surrealdb/rt.yaml
```

After this issue, I should be able to do this:
```yaml
files:
  - dashboard/rt.yaml
  - surrealdb/rt.yaml
```
